/**
 * hand-curated emoji keyword map for hangout planning titles.
 *
 * this is NOT a generic emoji picker vocabulary. every keyword is something a
 * person would plausibly type into "What's the plan?" when rallying friends:
 * food runs, drinks, pickup games, watch parties, game nights, trips,
 * birthdays. city names deliberately get nothing (except vegas, which is a
 * vibe, not a city).
 *
 * shape: [emoji, keywords[]]. keywords are lowercase. a keyword with spaces is
 * a phrase; phrases outrank single-token matches when the whole phrase appears
 * in the title (so "pool party" beats the billiards read of "pool").
 *
 * ENTRY ORDER MATTERS: when two emojis match at the same strength and position,
 * the one listed earlier here wins. put the iconic mapping first.
 *
 * matching rules live in emojiSuggest.ts; this file is data only so the map
 * can be tuned (or swapped for a bigger source) without touching the matcher.
 */
export const EMOJI_KEYWORDS: ReadonlyArray<readonly [string, readonly string[]]> = [
  // ---- food ----
  ['🍕', ['pizza', 'pizzas', 'pizzeria', 'slice', 'slices', 'pizza night']],
  ['🌮', ['taco', 'tacos', 'taqueria', 'taco tuesday']],
  ['🌯', ['burrito', 'burritos']],
  ['🍣', ['sushi', 'sashimi', 'omakase', 'hibachi']],
  ['🍜', ['ramen', 'pho', 'noodle', 'noodles', 'udon', 'thai']],
  ['🍔', ['burger', 'burgers', 'cheeseburger', 'smashburger']],
  ['🍗', ['wings', 'wing', 'chicken', 'fried chicken', 'wing night']],
  ['🍖', ['bbq', 'barbecue', 'barbeque', 'ribs', 'brisket', 'cookout', 'grill', 'grilling', 'smoker']],
  ['🥞', ['brunch', 'pancake', 'pancakes', 'waffle', 'waffles', 'ihop']],
  ['🍳', ['breakfast', 'diner', 'omelette']],
  ['🍽️', ['dinner', 'lunch', 'restaurant', 'reservation', 'resy', 'eat', 'food', 'feast']],
  ['🥘', ['potluck']],
  ['🍲', ['hotpot', 'hot pot', 'stew', 'soup']],
  ['🍝', ['pasta', 'spaghetti', 'italian', 'lasagna', 'carbonara']],
  ['🥟', ['dumpling', 'dumplings', 'dimsum', 'dim sum', 'gyoza']],
  ['🍛', ['curry']],
  ['🥙', ['shawarma', 'kebab', 'gyro', 'gyros', 'falafel']],
  ['🥗', ['salad', 'salads']],
  ['🥩', ['steak', 'steakhouse', 'kbbq', 'korean bbq']],
  ['🦞', ['lobster', 'seafood', 'crawfish', 'crawfish boil']],
  ['🦀', ['crab', 'crabs', 'crab boil']],
  ['🦪', ['oyster', 'oysters']],
  ['🍤', ['shrimp', 'tempura']],
  ['🥪', ['sandwich', 'sandwiches', 'deli', 'sub', 'subs', 'hoagie', 'hoagies']],
  ['🌭', ['hotdog', 'hotdogs', 'hot dog', 'hot dogs']],
  ['🧀', ['cheese', 'charcuterie', 'fondue', 'cheese board']],
  ['🥐', ['croissant', 'croissants', 'bakery', 'patisserie']],
  ['🍎', ['apple picking', 'orchard', 'cider']],
  ['🥡', ['takeout', 'take out']],
  ['🍦', ['ice cream', 'icecream', 'gelato', 'froyo', 'sundae']],
  ['🍩', ['donut', 'donuts', 'doughnut', 'doughnuts']],
  ['🍰', ['dessert', 'desserts', 'cheesecake']],
  ['🧁', ['cupcake', 'cupcakes']],
  ['🍪', ['cookie', 'cookies', 'baking', 'bake', 'cookie swap']],
  ['🧑‍🍳', ['cooking', 'cook', 'chef', 'cooking class', 'meal prep']],

  // ---- drinks ----
  ['🍺', ['beer', 'beers', 'brewery', 'breweries', 'pint', 'pints', 'ipa', 'craft beer']],
  ['🍻', ['drinks', 'happy hour', 'hh', 'bar', 'bar crawl', 'pub crawl', 'pub', 'pregame', 'kickback', 'oktoberfest', 'boys night', 'guys night']],
  ['🍷', ['wine', 'winery', 'vineyard', 'wine night', 'wine tasting']],
  ['🍸', ['cocktail', 'cocktails', 'martini', 'martinis', 'speakeasy', 'nightcap']],
  ['🍹', ['margarita', 'margaritas', 'margs', 'tiki']],
  ['🥃', ['whiskey', 'whisky', 'bourbon', 'scotch', 'shots', 'tequila', 'mezcal']],
  ['🥂', ['champagne', 'mimosa', 'mimosas', 'anniversary']],
  ['🍶', ['sake']],
  ['☕', ['coffee', 'cafe', 'espresso', 'latte', 'cappuccino', 'coffee run']],
  ['🍵', ['tea', 'matcha']],
  ['🧋', ['boba', 'bubble tea']],
  ['🥤', ['smoothie', 'smoothies']],

  // ---- sports: playing and watching ----
  ['🏀', ['basketball', 'bball', 'hoops', 'nba', 'march madness']],
  ['🏈', ['football', 'nfl', 'superbowl', 'super bowl', 'tailgate', 'fantasy', 'fantasy draft', 'fantasy football', 'game day']],
  ['⚽', ['soccer', 'futbol', 'world cup']],
  ['⚾', ['baseball', 'mlb', 'ballgame', 'batting cages']],
  ['🥎', ['softball']],
  ['🏒', ['hockey', 'nhl']],
  ['🏐', ['volleyball']],
  ['🎾', ['tennis', 'pickleball', 'padel']],
  ['⛳', ['golf', 'golfing', 'topgolf', 'driving range', 'mini golf', 'putt']],
  ['🎳', ['bowling']],
  ['🎱', ['pool', 'billiards', 'pool hall']],
  ['🏓', ['ping pong', 'pingpong', 'table tennis']],
  ['🥊', ['boxing', 'ufc', 'mma', 'fight night', 'kickboxing']],
  ['🥋', ['bjj', 'jiu jitsu', 'karate', 'judo', 'taekwondo', 'martial arts']],
  ['🏋️', ['gym', 'workout', 'lift', 'lifting', 'weights', 'crossfit']],
  ['🏃', ['run', 'running', 'jog', 'jogging', '5k', '10k', 'marathon', 'half marathon']],
  ['🚴', ['bike', 'biking', 'cycling', 'ride', 'bike ride', 'spin class', 'peloton']],
  ['🧘', ['yoga', 'pilates', 'meditation']],
  ['🧗', ['climbing', 'climb', 'bouldering', 'rock climbing']],
  ['🏊', ['swim', 'swimming', 'pool party']],
  ['🏄', ['surf', 'surfing']],
  ['⛷️', ['ski', 'skiing', 'slopes']],
  ['🏂', ['snowboard', 'snowboarding']],
  ['🛷', ['sled', 'sledding', 'snow tubing']],
  ['❄️', ['snow', 'snow day']],
  ['⛸️', ['ice skating', 'ice skate']],
  ['🛼', ['roller skating', 'rollerblading', 'roller rink']],
  ['🛹', ['skate', 'skating', 'skateboard', 'skatepark']],
  ['🥏', ['frisbee', 'disc golf', 'ultimate']],
  ['🏸', ['badminton']],
  ['🎣', ['fishing', 'fish', 'fly fishing']],
  ['🏹', ['archery']],
  ['🪓', ['axe throwing', 'axe', 'axes', 'hatchet']],
  ['🐎', ['horseback', 'horseback riding', 'horse', 'horses']],
  ['🏇', ['derby']],
  ['🤿', ['snorkel', 'snorkeling', 'scuba', 'diving']],
  ['🪂', ['skydiving', 'skydive']],
  ['🛶', ['kayak', 'kayaking', 'canoe', 'canoeing', 'paddle', 'paddleboard', 'rafting']],
  ['⛵', ['sail', 'sailing']],
  ['🚤', ['boat', 'boating', 'lake', 'lake day', 'jetski', 'jet ski', 'tubing']],
  ['🏆', ['playoffs', 'finals', 'championship']],

  // ---- games ----
  ['🃏', ['poker', 'poker night', 'cards', 'card night', 'blackjack', 'holdem', 'euchre', 'uno', 'spades', 'rummy']],
  ['🎲', ['board game', 'board games', 'boardgame', 'boardgames', 'game night', 'catan', 'monopoly', 'dice', 'yahtzee', 'tabletop']],
  ['🎮', ['game', 'games', 'gaming', 'gamer', 'video game', 'video games', 'xbox', 'playstation', 'ps5', 'nintendo', 'smash bros', 'mario kart', 'minecraft', 'fortnite', 'valorant', 'cod', 'warzone', 'lan party']],
  ['🐉', ['dnd', 'dungeons', 'dragons', 'pathfinder', 'ttrpg']],
  ['♟️', ['chess']],
  ['🧩', ['puzzle', 'puzzles', 'jigsaw']],
  ['🧱', ['lego', 'legos']],
  ['🗝️', ['escape room', 'escape rooms', 'escape']],
  ['🧠', ['trivia', 'trivia night', 'quiz', 'quiz night', 'jeopardy']],
  ['🎰', ['casino', 'vegas', 'gambling', 'slots']],
  ['🕹️', ['arcade', 'pinball', 'barcade']],
  ['🎯', ['darts']],
  ['🀄', ['mahjong']],

  // ---- media and entertainment ----
  ['🎬', ['movie', 'movies', 'film', 'films', 'cinema', 'flick', 'movie night', 'movie marathon']],
  ['🍿', ['binge', 'netflix', 'stream', 'streaming', 'watch party']],
  ['📺', ['tv', 'show', 'series', 'finale', 'episode', 'premiere', 'watch', 'tv night']],
  ['🎤', ['karaoke', 'open mic']],
  ['🎫', ['concert', 'tickets', 'tix', 'gig']],
  ['🎭', ['comedy', 'standup', 'stand up', 'improv', 'theater', 'theatre', 'musical', 'broadway']],
  ['🎸', ['band', 'guitar', 'band practice']],
  ['🎻', ['symphony', 'orchestra', 'opera']],
  ['🎶', ['music', 'jam', 'jam session']],
  ['🎷', ['jazz', 'sax', 'saxophone', 'blues']],
  ['🪩', ['club', 'clubbing', 'rave', 'edm', 'disco']],
  ['🎧', ['dj', 'dj set']],
  ['💃', ['dance', 'dancing', 'salsa', 'ballroom', 'line dancing']],
  ['🎪', ['fest', 'festival']],
  ['🎡', ['fair', 'carnival', 'state fair']],
  ['🎨', ['paint night', 'paint and sip', 'painting', 'art', 'pottery', 'ceramics', 'craft', 'crafts', 'craft night', 'drawing']],
  ['🏛️', ['museum', 'exhibit', 'gallery']],
  ['📚', ['book club', 'book', 'books', 'reading', 'library']],
  ['📸', ['photoshoot', 'photo shoot', 'photos', 'photography', 'photo walk', 'headshots']],

  // ---- outdoors ----
  ['🥾', ['hike', 'hiking', 'trail', 'trails', 'trek', 'backpacking']],
  ['🏕️', ['camp', 'camping', 'campsite', 'glamping', 'tent']],
  ['🔥', ['bonfire', 'campfire', 'firepit', 'fire pit', 'smores']],
  ['🏖️', ['beach', 'beach day', 'shore', 'boardwalk']],
  ['🧺', ['picnic']],
  ['🌳', ['park']],
  ['⛰️', ['mountain', 'mountains', 'summit']],
  ['🌅', ['sunrise', 'sunset', 'golden hour']],
  ['🔭', ['stargazing']],
  ['🌷', ['garden', 'gardening', 'botanical garden']],
  ['🌽', ['corn maze']],
  ['🐶', ['dog park', 'dog', 'dogs', 'puppy', 'puppies']],
  ['🚶', ['walk', 'stroll', 'hot girl walk']],

  // ---- occasions ----
  ['🎂', ['birthday', 'bday', 'cake', '21st', '30th', '40th', '50th']],
  ['🎉', ['party', 'celebration', 'celebrate', 'house party', 'surprise']],
  ['🎊', ['reunion']],
  ['💍', ['engagement', 'engaged', 'engagement party', 'proposal']],
  ['💒', ['wedding', 'reception']],
  ['👰', ['bachelorette', 'bridal shower']],
  ['🤵', ['bachelor party']],
  ['🎓', ['graduation', 'grad', 'grad party', 'commencement']],
  ['🏠', ['housewarming', 'house warming']],
  ['👋', ['farewell', 'goodbye', 'going away', 'send off', 'sendoff', 'last hurrah']],
  ['🎃', ['halloween', 'spooky', 'costume', 'pumpkin patch', 'haunted house', 'hayride']],
  ['🦃', ['thanksgiving', 'friendsgiving', 'turkey', 'turkey bowl']],
  ['🎄', ['christmas', 'xmas', 'holiday', 'holidays', 'holiday party', 'secret santa', 'white elephant']],
  ['🕎', ['hanukkah', 'chanukah']],
  ['🎆', ['nye', 'new year', 'new years', 'fireworks', 'fourth of july', '4th of july', 'july 4th']],
  ['💘', ['valentines', 'valentine', 'galentines']],
  ['🍀', ['patricks', 'paddys', 'pattys', 'st patricks']],
  ['🐣', ['easter', 'egg hunt']],
  ['👶', ['baby shower', 'gender reveal']],
  ['🎁', ['gift exchange']],
  ['🪅', ['fiesta', 'pinata', 'cinco', 'cinco de mayo']],

  // ---- travel ----
  ['🚗', ['road trip', 'roadtrip', 'day trip', 'drive']],
  ['✈️', ['flight', 'flights', 'airport', 'fly', 'layover', 'trip', 'travel']],
  ['🏝️', ['vacation', 'vacay', 'getaway', 'tropical']],
  ['🛳️', ['cruise']],
  ['🏨', ['hotel', 'staycation']],
  ['🏡', ['cabin', 'airbnb', 'lake house']],
  ['🎢', ['rollercoaster', 'coasters', 'theme park', 'amusement park', 'six flags']],
  ['🏰', ['disney', 'disneyland', 'disney world']],

  // ---- misc ----
  ['📖', ['study', 'studying', 'study group', 'cram']],
  ['💻', ['work session', 'work sesh', 'coworking', 'hackathon', 'hack night', 'coding']],
  ['⛪', ['church', 'mass', 'worship', 'bible study', 'small group']],
  ['🤝', ['volunteer', 'volunteering', 'food drive', 'food bank']],
  ['🛍️', ['shopping', 'mall', 'thrift', 'thrifting', 'outlets']],
  ['💆', ['spa', 'massage', 'spa day', 'facial', 'facials', 'self care']],
  ['🧖', ['sauna']],
  ['🧊', ['cold plunge']],
  ['💅', ['nails', 'mani', 'pedi', 'manicure', 'girls night', 'ladies night', 'gno']],
  ['🧶', ['knitting', 'crochet']],
  ['📦', ['moving', 'moving day', 'help me move']],
  ['🛌', ['sleepover', 'slumber party']],
]
